baseURL = 'https://charityshot.co.uk/'
languageCode = 'en-gb'
title = 'Photographer based in Hampshire, UK'
theme = 'gallery'
defaultTheme = 'light'

[params]
  [params.socialIcons]
    instagram = "https://www.instagram.com/char.ityshot"
    email = "mailto:hello@charityshot.co.uk"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
